# Generated by Django 4.2.1 on 2023-11-26 12:32

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=10, unique=True),
        ),
    ]
