# Generated by Django 4.2.1 on 2023-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderd_food',
            name='sub_total',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
